In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target
df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y
print(df.isnull().sum())
df.fillna(df.mean(), inplace=True)

# Chuẩn hóa
scaler = StandardScaler()
X = scaler.fit_transform(X)
# Chia dữ liệu thành tập train và test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)

# Tạo mô hình
# Mô hình KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
# Neighbours = 3 nghĩa là lấy 3 điểm gần nhất để xác định nhãn của điểm đó
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Confusion matrix: \n', confusion_matrix(y_test, y_pred))
print('Classification report: \n', classification_report(y_test, y_pred))
# đánh gia bằng cross- validation
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn, X, y, cv=5, scoring='accuracy')
print('Accuracy: ', scores.mean())

# Tại sao đánh giá bằng cross-validation lại thấp hơn so accuracy_score
# Vì accuracy_score chỉ đánh giá trên tập test, còn cross-validation đánh giá trên tập train
# Để đánh giá chính xác nhất, cần phải đánh giá trên cả    tập train và test (cross-validation) 
# Đánh giá trên tập test giúp ta biết mô hình có tốt không, còn đánh giá trên train giúp ta biết mô hình có overfitting không 


sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(120, 4)
(30, 4)
(120,)
Accuracy:  1.0
Confusion matrix: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy:  0.9533333333333334


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Tạo dữ liệu mẫu: Dùng dataset breast cancer (hoặc thay bằng dữ liệu của bạn)
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
X = data.data
y = data.target

# Chia dữ liệu thành tập huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Khởi tạo các mô hình
models = {
    "Linear Regression": LinearRegression(),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": GaussianNB(),
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier()
}

# Lưu kết quả
results = {}

# Huấn luyện và đánh giá từng mô hình
for name, model in models.items():
    model.fit(X_train, y_train)  # Huấn luyện
    if name == "Linear Regression":  # Chuyển đổi dự đoán sang nhãn phân loại
        y_pred = (model.predict(X_test) > 0.5).astype(int)
    else:
        y_pred = model.predict(X_test)  # Dự đoán trên tập kiểm tra
    
    # Lưu kết quả đánh giá
    results[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, model.predict_proba(X_test)[:, 1]) if hasattr(model, "predict_proba") else None
    }

# In kết quả
for name, metrics in results.items():
    print(f"Model: {name}")
    for metric, value in metrics.items():
        if value is not None:
            print(f"{metric}: {value:.2f}")
    print("-" * 30)


c:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Model: Linear Regression
Accuracy: 0.96
Precision: 0.95
Recall: 0.99
F1-Score: 0.97
------------------------------
Model: Logistic Regression
Accuracy: 0.96
Precision: 0.95
Recall: 0.99
F1-Score: 0.97
ROC-AUC: 1.00
------------------------------
Model: Naive Bayes
Accuracy: 0.97
Precision: 0.96
Recall: 1.00
F1-Score: 0.98
ROC-AUC: 1.00
------------------------------
Model: K-Nearest Neighbors
Accuracy: 0.96
Precision: 0.93
Recall: 1.00
F1-Score: 0.97
ROC-AUC: 1.00
------------------------------
Model: Decision Tree
Accuracy: 0.94
Precision: 0.96
Recall: 0.94
F1-Score: 0.95
ROC-AUC: 0.94
------------------------------


c:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
  File "c:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\subp